services:
  pimtool-aspnet:
    container_name: pimtool-aspnet
    image: ${DOCKER_USERNAME}/pimtool-aspnet:latest
    ports:
      - 8081:8080
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};uid=${DB_USERNAME};pwd=${DB_PASSWORD};database=${DB_NAME};TrustServerCertificate=True
      - Jwt__Key=${JWT_KEY}
      - Jwt__Issuer=${JWT_ISSUER}
      - Jwt__Audience=${JWT_AUDIENCE}
      - Jwt__ExpiryMinutes=256
    networks:
      - pim-tool-networks

networks:
  pim-tool-networks:
    name: pim_tool_networks
    external: true