on:
    push:
      branches: ["main"]
  
jobs:
    api-build:
      name: Build source code to Docker image
      runs-on: ubuntu-22.04 
      steps:
        - name: Checkout Develop
          uses: actions/checkout@v3
  
        - name: DockerHub Login
          uses: docker/login-action@v3.1.0
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_TOKEN}}
  
        - name: Build Image And Push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: PIMToolServerAPI/Dockerfile
            push: true
            tags: ${{secrets.DOCKER_USERNAME}}/pimtool-aspnet:latest
    
    api-deploy:
      name: Deploy Staging Admin To Google Service Server For Testing
      runs-on: arisa-server
      needs: api-build
      env:
        DB_HOST: ${{secrets.DB_HOST}}
        DB_USERNAME: ${{secrets.DB_USERNAME}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_NAME: ${{secrets.DB_NAME}}
        JWT_KEY: ${{secrets.JWT_KEY}}
        JWT_ISSUER: ${{secrets.JWT_ISSUER}}
        JWT_AUDIENCE: ${{secrets.JWT_AUDIENCE}}
      steps:
        - name: Checkout Develop
          uses: actions/checkout@v3
        - name: DockerHub Login
          uses: docker/login-action@v3.1.0
          with:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_TOKEN}}
        - name: Stop API
          run: docker compose -p pimtool-application down pimtool-aspnet --rmi all -v
          continue-on-error: true
        - name: Deploy API
          run: docker compose -p pimtool-application up -d pimtool-aspnet